name: build_deploy_reusable.yml
on:
  workflow_call:
    inputs:
      CLOUDHUB_ENVIRONMENT:
        required: true
        type: string
      GITHUB_ENVIRONMENT:
        required: true
        type: string                    
      CLOUDHUB_WORKERS:
        required: true
        type: string
      CLOUDHUB_WORKER_TYPE:
        required: true
        type: string                
      CLOUDHUB_REGION:
        required: true
        type: string                
      HTTP_PRIVATE_PORT:
        required: true
        type: string                        
    secrets:
      CLOUDHUB_USERNAME:
        required: true    
      CLOUDHUB_PASSWORD:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.GITHUB_ENVIRONMENT }}    
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.ref}}        
        
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        cache: 'maven'
        java-version: 8
        server-id: github

    - uses: s4u/maven-settings-action@v2.6.0
      with:
        servers: '[{"id": "mule-connected-app", "username": "${{ inputs.GITHUB_ENVIRONMENT}}", "password": "${{ inputs.GITHUB_ENVIRONMENT }}"}]'

    - name: JOB settings DETAILS
      run: |
        cat /home/runner/.m2/settings.xml
        
    - name: Clean Test for development branch
      if: ${{ github.event.ref == 'refs/heads/develop' }}
      run: mvn clean test               

    - name: Build and Test for development branch
      if: ${{ github.event.ref == 'refs/heads/develop' }}
      run: mvn clean package      

    - name: Build and Test for release and production
      if: ${{ github.event.ref != 'refs/heads/develop' }}
      run: mvn clean package -DskipTests      

    - name: Publish MUnit Coverage Reports
      if: ${{ github.event.ref == 'refs/heads/develop' }}
      uses: actions/upload-artifact@v2
      with:
        name: munit-coverage-reports
        path: target/site/munit/coverage/*

    - name: Publish MUnit Test Reports
      if: ${{ github.event.ref == 'refs/heads/develop' }}
      uses: actions/upload-artifact@v2
      with:
        name: munit-test-reports
        path: target/surefire-reports/*

    # Add email these reports, zip - TBD
        
    - name: Configure Git user
      if: ${{ github.event.ref != 'refs/heads/develop' }}
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        
    - name: prepare release and perform
      continue-on-error: true
      if: ${{ github.event.ref != 'refs/heads/develop' }}
      run: mvn -B release:prepare release:perform
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        
    - name: Deploy for ${{ github.event.ref }} branch
      run: |
        mvn -U -V -e -B -DskipTests deploy --file pom.xml -DmuleDeploy \
        -Danypoint.userName=${{ secrets.CLOUDHUB_USERNAME}} \
        -Danypoint.password=${{ secrets.CLOUDHUB_PASSWORD}} \
        -Dcloudhub.environment=${{ inputs.CLOUDHUB_ENVIRONMENT}} \
        -Dcloudhub.workerType=${{ inputs.CLOUDHUB_WORKER_TYPE}} \
        -Dcloudhub.workers=${{ inputs.CLOUDHUB_WORKERS}} \
        -Dcloudhub.region=${{ inputs.CLOUDHUB_REGION}} \
        -Dhttp.private.port=${{ inputs.HTTP_PRIVATE_PORT}} \
